jobs:
  pmd-code-scan:
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: '17'
    - continue-on-error: true
      id: pmd
      name: Run PMD
      uses: pmd/pmd-github-action@v1.4.0
      with:
        analyzeModifiedFilesOnly: false
        rulesets: rulesets/java/quickstart.xml
        sourcePath: src/main/java
    - continue-on-error: true
      name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: pmd-report.sarif
name: pmd
on:
  repository_dispatch:
    types: trigger-ga___pmd.yml
permissions:
  contents: read
